"""add_dedicated_profile_photo_to_vendor

Revision ID: 1a106b5cff00
Revises: a5a764ed6eae
Create Date: 2026-07-24 22:20:36.416319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a106b5cff00'
down_revision: Union[str, Sequence[str], None] = 'a5a764ed6eae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendor_profiles', sa.Column('profile_photo_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendor_profiles', 'profile_photo_url')
    # ### end Alembic commands ###
