"""make_booking_id_optional_on_messages

Revision ID: 2c83d3d4ea10
Revises: 5ccf605c5b87
Create Date: 2026-07-12 22:26:13.774481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c83d3d4ea10'
down_revision: Union[str, Sequence[str], None] = '5ccf605c5b87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
