"""create_all_database

Revision ID: 36d6639940a1
Revises: fad8d1fc0f89
Create Date: 2026-07-05 10:35:00.898008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36d6639940a1'
down_revision: Union[str, Sequence[str], None] = 'fad8d1fc0f89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('custom_event_type', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'custom_event_type')
    # ### end Alembic commands ###
