"""add_lat_lng_to_cities

Revision ID: 3d9a79aa27a3
Revises: a51c9c902070
Create Date: 2026-09-13 21:33:35.423562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d9a79aa27a3'
down_revision: Union[str, Sequence[str], None] = 'a51c9c902070'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cities', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('cities', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cities', 'longitude')
    op.drop_column('cities', 'latitude')
    # ### end Alembic commands ###
