"""make_booking_id_optional_on_messages

Revision ID: 5ccf605c5b87
Revises: 96acff0f9f96
Create Date: 2026-07-12 22:05:52.162546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ccf605c5b87'
down_revision: Union[str, Sequence[str], None] = '96acff0f9f96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'booking_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'booking_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
