"""add_category_to_event_posts

Revision ID: 6cf664b921dc
Revises: fc10920cf53b
Create Date: 2026-08-06 19:38:14.717545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cf664b921dc'
down_revision: Union[str, Sequence[str], None] = 'fc10920cf53b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_posts', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'event_posts', 'vendor_categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'event_posts', type_='foreignkey')
    op.drop_column('event_posts', 'category_id')
    # ### end Alembic commands ###
