"""add_unique_constraint_vendor_availability

Revision ID: 7382a69ac71e
Revises: edea90bec02c
Create Date: 2026-07-26 08:52:54.839110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7382a69ac71e'
down_revision: Union[str, Sequence[str], None] = 'edea90bec02c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_vendor_availability_date', 'vendor_availability', ['vendor_id', 'date'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_vendor_availability_date', 'vendor_availability', type_='unique')
    # ### end Alembic commands ###
