"""add_device_tracking_to_refresh_tokens table

Revision ID: 8867b5dc7ce5
Revises: 9685eea41588
Create Date: 2026-07-12 20:11:48.753119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8867b5dc7ce5'
down_revision: Union[str, Sequence[str], None] = '9685eea41588'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('device_info', sa.String(length=255), nullable=True))
    op.add_column('refresh_tokens', sa.Column('ip_address', sa.String(length=45), nullable=True))
    op.add_column('refresh_tokens', sa.Column('last_used_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('refresh_tokens', 'last_used_at')
    op.drop_column('refresh_tokens', 'ip_address')
    op.drop_column('refresh_tokens', 'device_info')
    # ### end Alembic commands ###
