"""add_dedicated_profile_photo_to_vendors

Revision ID: edea90bec02c
Revises: 1a106b5cff00
Create Date: 2026-07-24 23:23:48.274572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edea90bec02c'
down_revision: Union[str, Sequence[str], None] = '1a106b5cff00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
