"""add_unique_constraint_vendor_working_hours

Revision ID: f7457ecbd78d
Revises: 7382a69ac71e
Create Date: 2026-07-26 08:53:50.699546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7457ecbd78d'
down_revision: Union[str, Sequence[str], None] = '7382a69ac71e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_vendor_working_hours_day', 'vendor_working_hours', ['vendor_id', 'day_of_week'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_vendor_working_hours_day', 'vendor_working_hours', type_='unique')
    # ### end Alembic commands ###
