"""add_show_whatsapp_toggle_to_vendor

Revision ID: fc10920cf53b
Revises: f7457ecbd78d
Create Date: 2026-08-06 19:17:03.876981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc10920cf53b'
down_revision: Union[str, Sequence[str], None] = 'f7457ecbd78d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendor_profiles', sa.Column('show_whatsapp', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendor_profiles', 'show_whatsapp')
    # ### end Alembic commands ###
